### ISSUE TITLE
files/folders with exotic characters

### ISSUE THREAD

**Issue by t-flo** [t-flo/nxTransmission#5]

**Comment by uyjulian** [comment]
Horizon uses the PrFILE2 driver on eMMC and SDMC, which only supports Shift JIS as the encoding. This may be fixed if the filesystem driver is replaced (whenever Atmosphère gets around to it).

**Comment by t-flo** [comment]
@uyjulian Thanks! Also found this issue switchbrew/libnx#90. Adding a simple workaround now to replace any non ASCII character with a '_' in file names.
